### ISSUE TITLE
Compilation fails because of an outdated version of pbr

### ISSUE THREAD

**Issue by mattbasta** [indiscipline/zrtstr#3]
PBR fails to compile when building zrtstr due to this error:

```
error[E0283]: type annotations required: cannot resolve `std::string::String: std::convert::AsRef<_>`
   --> /Users/basta/.cargo/git/checkouts/pb-06f1c94bfc11587f/a1bf8ce/src/pb.rs:334:68
    |
334 |                             base = base + repeat!(self.bar_current.as_ref(), curr_count - 1) +
    |                                           -------------------------^^^^^^------------------- in this macro invocation

error: aborting due to previous error
```

Upgrading PBR to the latest version fixes the problem entirely. I don't know Rust well enough to contribute a proper fix, but fiddling with the PBR version and regenerating the `Cargo.lock` file made the compilation process succeed without any problems, and the tool works as expected.

**Comment by indiscipline** [comment]
Thanks for your interest in the program and your report. Sorry for being a bit late.

Fixed with #5 and v0.2.0
