### ISSUE TITLE
Optionally detect true mono in addition to faux-stereo

### ISSUE THREAD

**Issue by snoblenet** [indiscipline/zrtstr#8]
This tool looks very similar to what I was after.

Would it be possible for it to optionally detect true mono files in addition to faux-stereo files?

I'd roll up my sleeves myself but I have zero Rust experience.

**Comment by indiscipline** [comment]
Could you maybe explain what is your use-case for zrtstr? 
The only true-mono files are just the files with a single audio channel, and for this I suggest using ffprobe:
```
 ffprobe -hide_banner -select_streams a:0 -show_streams -v error  INPUT.wav | grep channels
```
The main advantage is that it can read almost any file format. Please, tell me if this solves your problem or not.

Thanks for your interest in the project!

**Comment by snoblenet** [comment]
Awesome. I'll check out `ffprobe`. My use case is I'd rather have true stereo versions of each track, when a true stereo exists, and I'm hoping to find all mono and `faux-stereo` versions in a time-efficient way.
